version: '3.8'
services:
  redis:
    image: redis:7
    ports: ['6379:6379']
  mysql:
    image:  mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    ports:  ['3306:3306']